### ISSUE TITLE
404 Not found 

### ISSUE THREAD

**Issue by 2metres** [cherihung/eslint-config-gatsby#1]
```sh
$ npm install --save-dev eslint-config-gatsby
npm ERR! code E404
npm ERR! 404 Not Found: eslint-config-gatsby@latest``

**Comment by joelbowen** [comment]
This appears to only work as a scoped package now:

`yarn add / npm i -D @cherihun/eslint-config-gatsby`

and in your eslintrc:

`"extends": ["@cherihung/gatsby"]`

**Comment by azevedo** [comment]
@joelbowen there's a typo

```
yarn add / npm i -D @cherihung/eslint-config-gatsby
```

**Comment by cherihung** [comment]
thanks for noticing. 
I've updated the Readme doc now to reflect better instruction.
